# This configuration builds and runs Components E2E tests only
pr: none

# Don't run CI for this config
trigger: none

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _TeamName
  value:  AspNetCore

jobs:
- template: jobs/default-build.yml
  parameters:
    condition: ne(variables['SkipTests'], 'true')
    jobName: Components_E2E_Test
    jobDisplayName: "Components E2E test"
    agentOs: Linux
    installNodeJs: true
    installJdk: true
    isTestingJob: true
    steps:
    - script: git submodule update --init
      displayName: Update submodules
    - script: src/Components/build.sh -ci -c Release
      displayName: Build Components
    - script: .dotnet/dotnet test ./src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj -c Release --logger trx
      displayName: Run E2E tests
    artifacts:
    - name: Components_E2E_Test_Logs
      path: artifacts/log/
      publishOnError: true
