#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _TeamName
  value:  AspNetCore

stages:
- stage: build
  displayName: Build
  jobs:

  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    # Test jobs
    - template: jobs/default-build.yml
      parameters:
        condition: ne(variables['SkipTests'], 'true')
        jobName: Components_Test
        jobDisplayName: "Test: Blazor E2E tests on Linux"
        agentOs: Linux
        isTestingJob: true
        installNodeJs: true
        installJdk: true
        cancelTimeoutInMinutes: 30
        buildArgs: --all --test /p:SkipHelixReadyTests=true /p:SkipIISNewHandlerTests=true /p:SkipIISTests=true
                   /p:SkipIISExpressTests=true /p:SkipIISNewShimTests=true /p:RunTemplateTests=false
        artifacts:
        - name: Components_Test_Dumps
          path: artifacts/dumps/
          publishOnError: true
          includeForks: true
        - name: Components_Test_Logs
          path: artifacts/log/
          publishOnError: true
          includeForks: true
        - name: Components_Test_Results
          path: artifacts/TestResults/
          publishOnError: true
          includeForks: true
